import type { Metadata } from "next";
import "../globals.css";
import { Providers } from "../../lib/redux/provider";
import { DM_Sans } from "next/font/google";
import Footer from "@/components/layout/footer";
import RootProviders from "@/components/providers";
import { Locale, routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Navbar from "@/components/layout/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DM_font = DM_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

type LocaleLayoutProps = {
  children: React.ReactNode;
} & { params: { locale: string } };

export default function LocaleLayout({ params: { locale }, children }: LocaleLayoutProps) {
  // Check if the locale is valid
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className={`${DM_font.variable} antialiased`}>
        <Providers>
          <RootProviders>
            <Navbar />
            {children}
            <Footer />
          </RootProviders>
        </Providers>
      </body>
    </html>
  );
}
